-- HDMI
set_property PACKAGE_PIN D19 [get_ports {TMDS[0]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDS[0]}]
set_property PACKAGE_PIN D20 [get_ports {TMDSB[0]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDSB[0]}]
set_property PACKAGE_PIN C20 [get_ports {TMDS[1]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDS[1]}]
set_property PACKAGE_PIN B20 [get_ports {TMDSB[1]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDSB[1]}]
set_property PACKAGE_PIN B19 [get_ports {TMDS[2]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDS[2]}]
set_property PACKAGE_PIN A20 [get_ports {TMDSB[2]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDSB[2]}]
set_property PACKAGE_PIN H16 [get_ports {TMDS[3]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDS[3]}]
set_property PACKAGE_PIN H17 [get_ports {TMDSB[3]}]					
	set_property IOSTANDARD TMDS_33 [get_ports {TMDSB[3]}]
set_property PACKAGE_PIN K17 [get_ports {sys_clk}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sys_clk}]

-- Pushbuttons from L->R : Y16, K19, P16, K18
set_property PACKAGE_PIN Y16 [get_ports {p1_up}]
set_property IOSTANDARD LVCMOS33 [get_ports {p1_up}]
set_property PACKAGE_PIN K19 [get_ports {p1_dn}]
set_property IOSTANDARD LVCMOS33 [get_ports {p1_dn}]
set_property PACKAGE_PIN P16 [get_ports {p2_up}]
set_property IOSTANDARD LVCMOS33 [get_ports {p2_up}]
set_property PACKAGE_PIN K18 [get_ports {p2_dn}]
set_property IOSTANDARD LVCMOS33 [get_ports {p2_dn}]

-- LEDs
set_property PACKAGE_PIN D18 [get_ports {p1_s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p1_s[1]}]
set_property PACKAGE_PIN G14 [get_ports {p1_s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p1_s[0]}]
set_property PACKAGE_PIN M15 [get_ports {p2_s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p2_s[1]}]
set_property PACKAGE_PIN M14 [get_ports {p2_s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p2_s[0]}]

-- Switches
set_property PACKAGE_PIN T16 [get_ports {Speed}]
set_property IOSTANDARD LVCMOS33 [get_ports {Speed}]
--set_property PACKAGE_PIN W13 [get_ports {A0}]
--set_property IOSTANDARD LVCMOS33 [get_ports {A0}]
--set_property PACKAGE_PIN P15 [get_ports {B1}]
--set_property IOSTANDARD LVCMOS33 [get_ports {B1}]
--set_property PACKAGE_PIN G15 [get_ports {B0}]
--set_property IOSTANDARD LVCMOS33 [get_ports {B0}]
